name: CI/CD (Docker, Next.js)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

env:
  OWNER: ${{ github.repository_owner }}
  REPO:  ${{ github.event.repository.name }}
  TAG_LATEST: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
  TAG_SHA:    ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (PAT)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}           # e.g., cassandracrawford
          password: ${{ secrets.GHCR_PAT }}    # PAT with write:packages

      - name: Show target (debug)
        run: |
          echo "Pushing to:"
          echo "  ${{ env.TAG_LATEST }}"
          echo "  ${{ env.TAG_SHA }}"

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.TAG_LATEST }}
            ${{ env.TAG_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
