name: CI/CD (Docker, Next.js)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Root-level perms (some org policies ignore job-scoped perms)
permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    # Only run this job on real pushes (not PRs)
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Show context (debug)
        run: |
          echo "event: ${{ github.event_name }}"
          echo "pushing to: ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}"

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
